[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-branch --cov-report=xml"
asyncio_mode = "auto"
console_output_style = "count"
pythonpath = "src"
required_plugins = ["pytest-cov>=4.0.0", "pytest-azurepipelines", "pytest-mock"]
testpaths = ["tests/"]

env = [
    "SERVER_NAME=LCA Test",
    "SERVER_HOST=http://test",
    "PROJECT_NAME=LCA Test",
    "POSTGRES_HOST=localhost",
    "POSTGRES_USER=postgresuser",
    "POSTGRES_PASSWORD=mypassword",
    "POSTGRES_DB=lca-assembly",
    "POSTGRES_PORT=5632",
    "AAD_OPENAPI_CLIENT_ID=b7fc0d3e-fdd9-4260-8b01-12cad623c64a",
    "AAD_APP_CLIENT_ID=40c35f10-9d17-43dc-bf6c-6208945c98c6",
    "AAD_TENANT_ID=11be1538-79d8-4939-82b8-b767805d825b",
    "AAD_TEST_CLIENT_SECRET=RmQ7Q~ejj0xaB566qjekYB6Oivq06Sk4Q69Hw",
    "ROUTER_URL=http://router.url",
]

[tool.coverage.run]
omit = ["src/import_data/*.py", "src/initialize.py", "src/main.py"]

[tool.black]
line-length = 120
target-version = ['py310']
extend-include = """
^/alembic
"""