apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.configmap }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ .Values.db.serviceName }}
  POSTGRES_DB: {{ .Values.db.databaseName }}
  POSTGRES_PORT: "{{ .Values.db.port }}"
  POSTGRES_SSL: "{{ .Values.db.ssl }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap }}
  namespace: {{ .Values.namespace }}
data:
  SERVER_NAME: {{- template "serverName" }}
  SERVER_HOST: "http://localhost"
  AAD_OPENAPI_CLIENT_ID: "b7fc0d3e-fdd9-4260-8b01-12cad623c64a"
  AAD_APP_CLIENT_ID: "40c35f10-9d17-43dc-bf6c-6208945c98c6"
  AAD_TENANT_ID: "11be1538-79d8-4939-82b8-b767805d825b"
  BACKEND_CORS_ORIGINS: '["{{ .Values.appProtocol}}://{{ .Values.appDomain }}"]'
