{{- if eq .Values.deployType "DEV" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  password: 'YWRnYWtqMjM1NGpoc2tsaDc4MzU0'
  username: 'cG9zdGdyZXN1c2Vy' #postgresuser
---
{{- else if eq .Values.deployType "PROD"}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: assembly-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dcd38769-96a2-4e96-87ba-44f2da80fd12"
    tenantId: "11be1538-79d8-4939-82b8-b767805d825b"
    keyvaultName: "lca-arkitema"
    objects: |
      array:
        - |
          objectName: assembly-postgres-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: assembly-postgres-password
          objectType: secret
          objectVersion: ""
  secretObjects:
    - data:
      - key: username
        objectName: assembly-postgres-username
      - key: password
        objectName: assembly-postgres-password
      secretName: {{ .Values.db.secret }}
      type: generic
# Sources:
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#validate-the-secrets
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
{{- end }}