"""empty message

Revision ID: 1333819c3cc7
Revises: e73bebac4f90
Create Date: 2022-07-07 17:00:09.201291

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1333819c3cc7"
down_revision = "e73bebac4f90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectepd",
        sa.Column("gwp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("date_updated", sa.Date(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kg_per_m3", sa.Float(), nullable=True),
        sa.Column("kg_per_m2", sa.Float(), nullable=True),
        sa.Column("thickness", sa.Float(), nullable=True),
        sa.Column("origin_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["epd.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projectepd_name"), "projectepd", ["name"], unique=False)
    op.add_column("assembly", sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint("assemblyepdlink_epd_id_fkey", "assemblyepdlink", type_="foreignkey")
    op.create_foreign_key("epd_id_link", "assemblyepdlink", "projectepd", ["epd_id"], ["id"])
    op.add_column("epd", sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("epd", sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("epd", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("epd", "id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("epd", "type")
    op.drop_column("epd", "region")
    op.drop_column("epd", "owner")
    op.drop_constraint("epd_id_link", "assemblyepdlink", type_="foreignkey")
    op.create_foreign_key("assemblyepdlink_epd_id_fkey", "assemblyepdlink", "epd", ["epd_id"], ["id"])
    op.alter_column("assemblyepdlink", "epd_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("assemblyepdlink", "assembly_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("assembly", "id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("assembly", "project_id")
    op.drop_index(op.f("ix_projectepd_name"), table_name="projectepd")
    op.drop_table("projectepd")
    # ### end Alembic commands ###
