"""empty message

Revision ID: 1c9cfc006c7e
Revises: b3cd3ee4c393
Create Date: 2023-10-09 08:59:47.167612

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c9cfc006c7e"
down_revision = "b3cd3ee4c393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "epd", sa.Column("is_transport", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false())
    )
    op.add_column(
        "projectepd", sa.Column("is_transport", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectepd", "is_transport")
    op.drop_column("epd", "is_transport")
    # ### end Alembic commands ###
