"""empty message

Revision ID: 39ca0db4e14b
Revises: b8c9561a88f9
Create Date: 2023-10-10 11:15:43.767466

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "39ca0db4e14b"
down_revision = "b8c9561a88f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectassemblyepdlink", sa.Column("transport_epd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_foreign_key(
        "projectassemblyepdlink_projectepd_fkey", "projectassemblyepdlink", "projectepd", ["transport_epd_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projectassemblyepdlink_projectepd_fkey", "projectassemblyepdlink", type_="foreignkey")
    op.drop_column("projectassemblyepdlink", "transport_epd_id")
    # ### end Alembic commands ###
