"""empty message

Revision ID: 6f26c2bc974f
Revises: b322f89f3716
Create Date: 2022-09-28 12:50:10.861238

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f26c2bc974f"
down_revision = "b322f89f3716"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assembly", "life_time", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("assembly", "unit", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "assembly", "conversion_factor", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.add_column("assemblyepdlink", sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column(
        "assemblyepdlink", "conversion_factor", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column("assemblyepdlink", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("projectepd", "source_data", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projectepd", "source_data", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("assemblyepdlink", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "assemblyepdlink", "conversion_factor", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.drop_column("assemblyepdlink", "id")
    op.alter_column(
        "assembly", "conversion_factor", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column("assembly", "unit", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("assembly", "life_time", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True)
    # ### end Alembic commands ###
