"""empty message

Revision ID: 8b30210328c5
Revises: 1333819c3cc7
Create Date: 2022-07-12 15:27:13.625465

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b30210328c5"
down_revision = "1333819c3cc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assembly", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assembly", "description")
    # ### end Alembic commands ###
