"""empty message

Revision ID: 8c4f3d1dadf6
Revises: 39ca0db4e14b
Create Date: 2023-10-23 12:33:19.462767

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c4f3d1dadf6"
down_revision = "39ca0db4e14b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("projectassemblyepdlink_pkey", "projectassemblyepdlink", type_="primary")
    op.create_primary_key("projectassemblyepdlink_pkey", "projectassemblyepdlink", ["assembly_id", "epd_id", "id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("projectassemblyepdlink_pkey", "projectassemblyepdlink", type_="primary")
    op.create_primary_key("projectassemblyepdlink_pkey", "projectassemblyepdlink", ["assembly_id", "epd_id"])

    # ### end Alembic commands ###
