"""empty message

Revision ID: a425dcfcd693
Revises: d117ab2ed26b
Create Date: 2022-05-11 15:44:09.189181

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a425dcfcd693"
down_revision = "d117ab2ed26b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assemblyepdlink",
        sa.Column("assembly_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("epd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assembly_id"],
            ["assembly.id"],
        ),
        sa.ForeignKeyConstraint(
            ["epd_id"],
            ["epd.id"],
        ),
        sa.PrimaryKeyConstraint("assembly_id", "epd_id"),
    )
    op.add_column("assembly", sa.Column("meta_fields", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("assembly", sa.Column("life_time", sa.Float(), nullable=True))
    op.add_column("assembly", sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("assembly", sa.Column("conversion_factor", sa.Float(), nullable=True))
    op.add_column("epd", sa.Column("gwp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("epd", sa.Column("expiration_date", sa.Date(), nullable=False))
    op.add_column("epd", sa.Column("date_updated", sa.Date(), nullable=False))
    op.add_column("epd", sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("epd", "id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("epd", "source")
    op.drop_column("epd", "date_updated")
    op.drop_column("epd", "expiration_date")
    op.drop_column("epd", "version")
    op.drop_column("epd", "gwp_by_phases")
    op.alter_column("assembly", "id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("assembly", "conversion_factor")
    op.drop_column("assembly", "unit")
    op.drop_column("assembly", "life_time")
    op.drop_column("assembly", "meta_fields")
    op.drop_table("assemblyepdlink")
    # ### end Alembic commands ###
