"""empty message

Revision ID: b322f89f3716
Revises: a68b8abea315
Create Date: 2022-09-06 13:16:59.333671

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b322f89f3716"
down_revision = "a68b8abea315"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("epd", sa.Column("odp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("ap_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("ep_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("pocp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("penre_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("pere_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("meta_fields", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("epd", sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("epd", sa.Column("source_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("projectepd", sa.Column("odp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("ap_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("ep_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("pocp_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("penre_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("pere_by_phases", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("meta_fields", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("projectepd", sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("projectepd", sa.Column("source_data", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectepd", "source_data")
    op.drop_column("projectepd", "unit")
    op.drop_column("projectepd", "meta_fields")
    op.drop_column("projectepd", "pere_by_phases")
    op.drop_column("projectepd", "penre_by_phases")
    op.drop_column("projectepd", "pocp_by_phases")
    op.drop_column("projectepd", "ep_by_phases")
    op.drop_column("projectepd", "ap_by_phases")
    op.drop_column("projectepd", "odp_by_phases")
    op.drop_column("epd", "source_data")
    op.drop_column("epd", "unit")
    op.drop_column("epd", "meta_fields")
    op.drop_column("epd", "pere_by_phases")
    op.drop_column("epd", "penre_by_phases")
    op.drop_column("epd", "pocp_by_phases")
    op.drop_column("epd", "ep_by_phases")
    op.drop_column("epd", "ap_by_phases")
    op.drop_column("epd", "odp_by_phases")

    # ### end Alembic commands ###
