"""empty message

Revision ID: b3cd3ee4c393
Revises: 7523b7b167ae
Create Date: 2023-09-25 17:07:07.174075

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b3cd3ee4c393"
down_revision = "7523b7b167ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assembly",
        sa.Column("meta_fields", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("life_time", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversion_factor", sa.Float(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assembly_name"), "assembly", ["name"], unique=False)
    op.create_table(
        "assemblyepdlink",
        sa.Column("conversion_factor", sa.Float(), nullable=False),
        sa.Column("reference_service_life", sa.Integer(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transport_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transport_distance", sa.Float(), nullable=True),
        sa.Column("transport_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assembly_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("epd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assembly_id"],
            ["assembly.id"],
        ),
        sa.ForeignKeyConstraint(
            ["epd_id"],
            ["epd.id"],
        ),
        sa.PrimaryKeyConstraint("id", "assembly_id", "epd_id"),
    )
    op.add_column("projectassembly", sa.Column("origin_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key("projectassembly_origin_id_fkey", "projectassembly", "assembly", ["origin_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projectassembly_origin_id_fkey", "projectassembly", type_="foreignkey")
    op.drop_column("projectassembly", "origin_id")
    op.drop_table("assemblyepdlink")
    op.drop_index(op.f("ix_assembly_name"), table_name="assembly")
    op.drop_table("assembly")
    # ### end Alembic commands ###
