"""empty message

Revision ID: e73bebac4f90
Revises: a425dcfcd693
Create Date: 2022-05-17 16:43:27.051244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e73bebac4f90'
down_revision = 'a425dcfcd693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assembly_name'), 'assembly', ['name'], unique=False)
    op.add_column('assemblyepdlink', sa.Column('conversion_factor', sa.Float(), nullable=True))
    op.create_index(op.f('ix_epd_name'), 'epd', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epd_name'), table_name='epd')
    op.alter_column('epd', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assemblyepdlink', 'epd_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assemblyepdlink', 'assembly_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assemblyepdlink', 'conversion_factor')
    op.drop_index(op.f('ix_assembly_name'), table_name='assembly')
    op.alter_column('assembly', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
