"""empty message

Revision ID: e76a2af25d73
Revises: c4220702a2a1
Create Date: 2023-07-10 17:55:04.491124

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e76a2af25d73"
down_revision = "c4220702a2a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assemblyepdlink", sa.Column("reference_service_life", sa.Integer(), nullable=True))
    op.add_column("assemblyepdlink", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assemblyepdlink", "description")
    op.drop_column("assemblyepdlink", "reference_service_life")
    # ### end Alembic commands ###
