"""empty message

Revision ID: e9fd94a0cdca
Revises: 8b30210328c5
Create Date: 2022-08-08 16:50:19.958423

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9fd94a0cdca"
down_revision = "8b30210328c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assemblyepdlink", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assemblyepdlink", "name")
    # ### end Alembic commands ###
